#!/usr/bin/expect -f
set timeout 120
spawn npx vercel --prod
expect {
    "Set up and deploy" { send "y\r"; exp_continue }
    "Which scope do you want to deploy to" { send "\r"; exp_continue }
    "Link to existing project" { send "n\r"; exp_continue }
    "What's your project's name" { send "ihms-backend\r"; exp_continue }
    "In which directory is your code located" { send "\r"; exp_continue }
    "Want to override the settings" { send "n\r"; exp_continue }
    eof { }
}
